# Generated by Django 4.2.8 on 2025-05-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories_name',
            field=models.CharField(choices=[('Event', 'Event'), ('Knowledge', 'Knowledge'), ('Course', 'Course'), ('News', 'News')], default='Knowledge', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('planned', 'Planned'), ('reject', 'Reject')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('author', 'Author'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
