# Generated by Django 5.1.6 on 2025-05-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_api', '0002_user_avatar_alter_post_categories_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories_name',
            field=models.CharField(choices=[('event', 'Event'), ('knowledge', 'Knowledge'), ('course', 'Course'), ('news', 'News'), ('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('reading', 'Reading'), ('writing', 'Writing'), ('exams', 'English Exams'), ('conversational', 'Conversational English'), ('business', 'Business English'), ('culture', 'English Culture'), ('resources', 'Free Resources'), ('community', 'Community'), ('ielts', 'IELTS'), ('toeic', 'TOEIC'), ('toefl', 'TOEFL'), ('cambridge', 'Cambridge'), ('pronunciation', 'Pronunciation'), ('idioms', 'Idioms'), ('phrasal_verbs', 'Phrasal Verbs'), ('podcasts', 'Podcasts'), ('videos', 'Videos'), ('apps', 'Apps'), ('books', 'Books')], default='knowledge', max_length=100),
        ),
    ]
